version: "3"

services:
    app:
        image: 'bitnami/nginx'
        ports:
            - '80:8080'
        links:
            - phpfpm
        volumes:
            - ./logs/access.log:/opt/bitnami/nginx/logs/myapp-access.log
            - ./logs/error.log:/opt/bitnami/nginx/logs/myapp-error.log
            - ./docker/nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
            - ./:/myapps
#            - /media/skey/Elements/panoramas:/myapps/storage/app/public/panoramas
    phpfpm:
        image: 'bitnami/php-fpm'
        ports:
            - '9000:9000'
        volumes:
            - ./:/myapps
            - ./docker/php/php.ini:/opt/bitnami/php/etc/php.ini
    db:
        image: 'mariadb'
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pass